project:
  type: website
  output-dir: docs

website:
  title: "Kishore Kumar Jagadeesan"
  site-url: jkkishore85.github.io
  repo-url: https://github.com/jkkishore85/jkkishore85.github.io
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@kishorejag"
    site: "@kishorejag"
    title: "Kishore Kumar Jagadeesan"
  open-graph: true
  cookie-consent: true
  google-analytics: G-QVQJ5QYQZQ
  navbar:
    tools:
      - icon: github
        href: https://github.com/jkkishore85
      - icon: linkedin
        href: https://www.linkedin.com/in/jkishore/
      - icon: twitter-x
        href: https://x.com/kishorejag
      - icon: envelope
        href: mailto:jkkishore85@gmail.com
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: posts.qmd
        text: Blog
      - href: workshops.qmd
        text: Talks & Workshops
      - href: tutorials.qmd
        text: Tutorials
      - href: publications.qmd
        text: Publications
  page-footer: 
    background: light
    left: © Copyright 2024, Kishore Kumar Jagadeesan
    right: This website made using [Quarto®](https://quarto.org/) with ❤️, by [Kishore Kumar Jagadeesan](https://github.com/jkkishore85/){target=_blank}

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full
    link-external-newwindow: true
    html-math-method: katex
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-link: true
    df-print: paged
    toc: true
    toc-depth: 2
    toc-expand: 2
    toc-title: On this page
    toc-location: left
    filters:
      - social-share
    share:
      permalink: "https://jkkishore85.github.io/"
      description: "Kishore Kumar Jagadeesan's website"
      twitter: false
      facebook: false
      reddit: false
      stumble: false
      tumblr: false
      linkedin: false
      email: false
      mastodon: false

editor: visual

