---
title: "Publications"
layout: page
---
# Peer-reviewed Publications 
1.  [Jagadeesan, KK,]{.underline} Elliss, H., Standerwick, R, Robertson, M, Barden, R & Kasprzyk-Hordern, B Wastewater-Based Proteomics: A Proof-of-Concept for Advancing Early Warning System for Infectious Diseases and Immune Response Monitoring, Hazardous Materials Letters, 2024 <https://doi.org/10.1016/j.hazl.2024.100108>
2.  Ceolotto, N, Dollamore, P, Hold, A, Balne, B, [Jagadeesan, KK]{.underline}, Standerwick, R, Robertson, M, Barden, R & Kasprzyk-Hordern, B 2024, 'A new Wastewater-Based Epidemiology workflow to estimate community wide non-communicable disease prevalence using pharmaceutical proxy data', Journal of Hazardous Materials, vol. 461, 132645. <https://doi.org/10.1016/j.jhazmat.2023.132645>
3.  Wattanayon, R, Proctor, K, [Jagadeesan, K,]{.underline} Barden, R & Kasprzyk-Hordern, B 2023, 'An integrated One Health framework for holistic evaluation of risks from antifungal agents in a large-scale multi-city study', Science of the Total Environment, vol. 900, 165752. [https://doi.org/10.1016/j.scitotenv.2023.165752](#0)
4.  Sims, N, Kannan, A, Holton, E, [Jagadeesan, K]{.underline}, Mageiros, L, Standerwick, R, Craft, T, Barden, R, Feil, EJ & Kasprzyk-Hordern, B 2023, 'Antimicrobials and antimicrobial resistance genes in a one-year city metabolism longitudinal study using wastewater-based epidemiology', Environmental Pollution, vol. 333, 122020. <https://doi.org/10.1016/j.envpol.2023.122020>
5.  Sims, N, Holton, E, [Jagadeesan, K]{.underline}, Standerwick, R, Barden, R & Kasprzyk-Hordern, B 2023, 'Community infectious disease treatment with antimicrobial agents – A longitudinal one year study of antimicrobials in two cities via wastewater-based epidemiology', Journal of Hazardous Materials, vol. 454, 131461. [https://doi.org/10.1016/j.jhazmat.2023.131461](#0)
6.  [Jagadeesan, K,]{.underline} Barden, R & Kasprzyk-Hordern, B 2023, 'PERK: An R/Shiny application to predict and visualise concentrations of pharmaceuticals in the aqueous environment', Science of the Total Environment, vol. 875, 162352. [https://doi.org/10.1016/j.scitotenv.2023.162352](#0)
7.  Kasprzyk-Hordern, B, Sims, N, Farkas, K, Jagadeesan, KK, Proctor, K, Wade, MJ & Jones, DL 2023, 'Wastewater-based epidemiology for comprehensive community health diagnostics in a national surveillance study: mining biochemical markers in wastewater.', Journal of Hazardous Materials, vol. 450, 130989. [https://doi.org/10.1016/j.jhazmat.2023.130989](#0)
8.  Kannan, A.;  Sims, N.;  Hold, A. J.;  [Jagadeesan, K]{.underline}.;  Standerwick, R.;  Barden, R.; Kasprzyk-Hordern, B., The burden of city's pain treatment – A longitudinal one year study of two cities via wastewater-based epidemiology. Water Res. 2023, 229, 119391 [https://doi.org/10.1016/j.watres.2022.119391](#0)
9.  [Jagadeesan, K. K]{.underline}.;  Grant, J.;  Griffin, S.;  Barden, R.; Kasprzyk-Hordern, B., PrAna: an R package to calculate and visualize England NHS primary care prescribing data. BMC Med Inform Decis Mak 2022, 22 (1), 5. [https://doi.org/10.1186/s12911-021-01727-z](#0)
10. Kasprzyk-Hordern, B.;  Proctor, K.;  [Jagadeesan, K]{.underline}.;  Edler, F.;  Standerwick, R.; Barden, R., Human population as a key driver of biochemical burden in an inter-city system: Implications for One Health concept. J Hazard Mater 2022, 429, 127882
11. Holton, E.;  Sims, N.;  [Jagadeesan, K.;]{.underline}  Standerwick, R.; Kasprzyk-Hordern, B., Quantifying community-wide antimicrobials usage via wastewater-based epidemiology. J Hazard Mater 2022, 436, 129001 [https://doi.org/10.1016/j.jhazmat.2021.127882](#0)
12. Kasprzyk-Hordern, B.;  Proctor, K.;  [Jagadeesan, K.;]{.underline}  Watkins, S.;  Standerwick, R.;  Barden, R.; Barnett, J., Diagnosing Down-the-Drain Disposal of Unused Pharmaceuticals at a River Catchment Level: Unrecognized Sources of Environmental Contamination That Require Nontechnological Solutions. Environ Sci Technol 2021, 55 (17), 11657-11666 <https://doi.org/10.1021/acs.est.1c01274>
13. Gibbon, M. J.;  Couto, N.;  David, S.;  Barden, R.;  Standerwick, R.;  [Jagadeesan, K]{.underline}.;  Birkwood, H.;  Dulyayangkul, P.;  Avison, M. B.;  Kannan, A.;  Kibbey, D.;  Craft, T.;  Habib, S.;  Thorpe, H. A.;  Corander, J.;  Kasprzyk-Hordern, B.; Feil, E. J., A high prevalence of bla(OXA-48) in Klebsiella (Raoultella) ornithinolytica and related species in hospital wastewater in South West England. Microb Genom 2021, 7 (3) <https://doi.org/10.1099/mgen.0.000509>
14. Kasprzyk-Hordern, B.;  Proctor, K.;  [Jagadeesan, K]{.underline}.;  Lopardo, L.;  O'Daly, K. J.;  Standerwick, R.; Barden, R., Estimation of community-wide multi-chemical exposure via water-based chemical mining: Key research gaps drawn from a comprehensive multi-biomarker multi-city dataset. Environ Int 2021, 147, 106331 [https://doi.org/10.1016/j.envint.2020.106331](#0)
15. Rice, J.;  Kannan, A. M.;  Castrignano, E.;  [Jagadeesan, K.;]{.underline} Kasprzyk-Hordern, B., Wastewater-based epidemiology combined with local prescription analysis as a tool for temporalmonitoring of drugs trends - A UK perspective. Sci Total Environ 2020, 735, 139433 <https://doi.org/10.1016/j.scitotenv.2020.139433>
16. [Jagadeesan, K. K]{.underline}.;  Rossetti, C.;  Abdel Qader, A.;  Reubsaet, L.;  Sellergren, B.;  Laurell, T.; Ekstrom, S., Filter Plate-Based Screening of MIP SPE Materials for Capture of the Biomarker Pro-Gastrin-Releasing Peptide. SLAS Discov 2017, 22 (10), 1253-1261  [https://doi.org/10.1177/2472555216689494](#0)
17. [Jagadeesan, K. K.;]{.underline} Ekstrom, S., MALDIViz: A Comprehensive Informatics Tool for MALDI-MS Data Visualization and Analysis. SLAS Discov 2017, 22 (10), 1246-1252 [https://doi.org/10.1177/2472555217727517](#0)
18. Duarte, M.;  [Jagadeesan, K. K]{.underline}.;  Billing, J.;  Yilmaz, E.;  Laurell, T.; Ekstrom, S., Solid-phase extraction of the alcohol abuse biomarker phosphatidylethanol using newly synthesized polymeric sorbent materials containing quaternary heterocyclic groups. J Chromatogr A 2017, 1519, 1-8 [https://doi.org/10.1016/j.chroma.2017.08.051](#0)
19. Shen, X.;  Huang, C.;  Shinde, S.;  [Jagadeesan, K. K]{.underline}.;  Ekstrom, S.;  Fritz, E.; Sellergren, B., Catalytic Formation of Disulfide Bonds in Peptides by Molecularly Imprinted Microgels at Oil/Water Interfaces. ACS Appl Mater Interfaces 2016, 8 (44), 30484-30491 <https://doi.org/10.1021/acsami.6b10131>
20. [Jagadeesan, K. K]{.underline}.;  Wierzbicka, C.;  Laurell, T.;  Sellergren, B.;  Shinde, S.; Ekstrom, S., Multiplexed MALDI-MS arrays for screening of MIP solid phase extraction materials. J Chromatogr B Analyt Technol Biomed Life Sci 2016, 1021, 213-220 [https://doi.org/10.1016/j.jchromb.2015.10.033](#0)
21. Kumar, S.;  [Jagadeesan, K. K]{.underline}.;  Joshi, A. G.; Sumana, G., Immuno-CoPS (conducting paper strips) for futuristic cost-effective cancer diagnostics. RSC Advances 2013, 3 (29), 11846-11853 <https://doi.org/10.1039/C3RA40491A>
22. [Jagadeesan, K. K]{.underline}.;  Kumar, S.; Sumana, G., Application of conducting paper for selective detection of troponin. Electrochemistry Communications 2012, 20, 71-74 <https://doi.org/10.1016/j.elecom.2012.03.041>
